apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: local-services
  namespace: argocd
spec:
  generators:
    - scmProvider:
        github:
          organization: Infra-Reis
          allBranches: false
          tokenRef:
            secretName: github-token
            key: token
        filters:
          - pathsExist:
              - deploy.values.yaml
  template:
    metadata:
      name: "{{repository}}-app"
    spec:
      project: default
      destination:
        server: https://kubernetes.default.svc
        namespace: local-services
      sources:
        - repoURL: https://github.com/wellrcosta/infra-local.git
          targetRevision: main
          path: charts/app
          helm:
            valueFiles:
              - $values/deploy.values.yaml
        - repoURL: "{{url}}"
          targetRevision: "{{branch}}"
          ref: values
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
      syncOptions:
        - CreateNamespace=true
